POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "felipe@test.com",
    "password": "123456"
}

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "Pinha",
    "email": "felipe_pc7@hotmail.com",
    "password": "123456"
}

###

GET http://localhost:3000/user/password/random
Content-Type: application/json

###

POST http://localhost:3000/user/password/forgot
Content-Type: application/json

{
    "email": "felipe_pc7@hotmail.com"
}