POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Arnaldo",
    "email": "arnaldo@test.com",
    "password": "123456"
}
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "felipe@test.com",
    "password": "123456"
}


###

GET http://localhost:3000/auth/random
Content-Type: application/json